
jobs:
  - name: manifest-1
    type: manifest
    steps:
      - IN: nginx-image-1
      - TASK: managed

  - name: manifest-2
    type: manifest
    steps:
      - IN: manifest-1
      - TASK: managed
      
  - name: manifest-3
    type: manifest
    steps:
      - IN: nginx-image-2
      - TASK: managed
      
  - name: manifest-4
    type: manifest
    steps:
      - IN: manifest-3
      - TASK: managed     
      
  - name: manifest-5
    type: manifest
    steps:
      - IN: manifest-2
      - IN: manifest-4
      - TASK: managed        
      
