
jobs:
  - name: runSh-1
    type: runSh
    steps:
      - TASK:
        - script: sleep 1
      - IN: nginx-image-1
      
  - name: runSh-2
    type: runSh
    steps:
      - TASK:
        - script: sleep 1
      - IN: runSh-1
      
      
  - name: runSh-3
    type: runSh
    steps:
      - TASK:
        - script: sleep 1
      - IN: nginx-image-2
      
      
  - name: runSh-4
    type: runSh
    steps:
      - TASK:
        - script: sleep 1
      - IN: runSh-3     

  - name: runSh-5
    type: runSh
    steps:
      - TASK:
        - script: sleep 1
      - IN: runSh-4
      - IN: runSh-2
